//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Access_Layer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IsOruDbEntities : DbContext
    {
        public IsOruDbEntities()
            : base("name=IsOruDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Access> Access { get; set; }
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<Comment> Comment { get; set; }
        public virtual DbSet<Meeting> Meeting { get; set; }
        public virtual DbSet<Post> Post { get; set; }
        public virtual DbSet<Post_PostType> Post_PostType { get; set; }
        public virtual DbSet<PostType> PostType { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<User_Access> User_Access { get; set; }
        public virtual DbSet<User_Meeting> User_Meeting { get; set; }
    }
}
