//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Access_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Post_Comment
    {
        public int UPCId { get; set; }
        public int PostId { get; set; }
        public int CommentId { get; set; }
    
        public virtual Comment Comment { get; set; }
        public virtual Post Post { get; set; }
    }
}
