//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Access_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Access
    {
        public int User_PostId { get; set; }
        public int UserId { get; set; }
        public int AccessId { get; set; }
    
        public virtual Access Access { get; set; }
        public virtual User User { get; set; }
    }
}
